# Generated by Django 3.2.9 on 2023-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0, verbose_name='用户ID')),
                ('bookid', models.IntegerField(default=0, verbose_name='图书ID')),
                ('hitnum', models.IntegerField(default=0, verbose_name='点击次数')),
            ],
            options={
                'verbose_name': '点击量',
                'verbose_name_plural': '点击量',
            },
        ),
    ]
