# Generated by Django 3.2.9 on 2023-06-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0003_hit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hit',
            new_name='hits',
        ),
    ]
